info:
  app:
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    id: 100
    name: '@project.name@'
    response: http://localhost:10410/msoempleado/v1/errors/
    version: '@project.version@'

spring:
  config:
    activate:
      on-profile: dev, qa, prod
  mvc:
   pathmatch:
     matching-strategy: ANT_PATH_MATCHER
      
server:
  servlet:
    context-path: /@project.name@/v1
  port: 10410